# Generated by Django 5.1.15 on 2026-04-17 22:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Synthetic opaque identifier.', max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(25)])),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='O', max_length=1)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('school', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='RiskPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveSmallIntegerField(default=75, help_text='Total stress score at or above which a case is High Risk.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_policies_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk policy',
                'verbose_name_plural': 'Risk policies',
            },
        ),
        migrations.CreateModel(
            name='StressAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_pressure', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('social_anxiety', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('home_environment', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('total_score', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('workflow_state', models.CharField(choices=[('intake', 'Intake'), ('assessment', 'Assessment'), ('intervention', 'Intervention Planning'), ('follow_up', 'Follow-up'), ('closed', 'Closed')], default='intake', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High Risk')], default='low', max_length=10)),
                ('risk_explanation', models.TextField(blank=True, help_text='Human-readable reason why the risk level was assigned. Populated automatically by the rule engine.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(help_text='School staff member who produced the assessment.', on_delete=django.db.models.deletion.PROTECT, related_name='submitted_assessments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='cases.student')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('intake', 'Case created'), ('state_change', 'State change'), ('appointment', 'Appointment update'), ('reminder', 'Automatic reminder'), ('note', 'Note added'), ('denied', 'Action denied')], max_length=20)),
                ('from_state', models.CharField(blank=True, max_length=20)),
                ('to_state', models.CharField(blank=True, max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_events', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.stressassessment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_appointments', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='cases.stressassessment')),
            ],
            options={
                'ordering': ('scheduled_for',),
            },
        ),
        migrations.AddIndex(
            model_name='stressassessment',
            index=models.Index(fields=['workflow_state', 'risk_level'], name='cases_stres_workflo_5ebe6d_idx'),
        ),
        migrations.AddIndex(
            model_name='stressassessment',
            index=models.Index(fields=['-created_at'], name='cases_stres_created_35d9e8_idx'),
        ),
    ]
