# Generated by Django 5.1.15 on 2026-06-07 19:30

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Synthetic opaque identifier (e.g. STU-0001-TUN).', max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)])),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other / Not specified')], default='O', max_length=1)),
                ('grade', models.CharField(blank=True, help_text="Grade / class level (e.g. '9e', '2ème Sec').", max_length=20)),
                ('school', models.CharField(max_length=100)),
                ('region', models.CharField(help_text='Tunisian governorate.', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='SERSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(blank=True, help_text="e.g. 'Week 12 / 2025' or 'March 2025'.", max_length=30)),
                ('unexcused_absences', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)])),
                ('grade_drop_points', models.PositiveSmallIntegerField(default=0, help_text='Points dropped from previous period average (0–20).', validators=[django.core.validators.MaxValueValidator(20)])),
                ('disciplinary_flags', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('wellbeing_score', models.PositiveSmallIntegerField(default=5, help_text='Self-reported or staff-observed well-being (1=very low, 10=excellent).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('sers_score', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High Risk')], default='low', max_length=10)),
                ('risk_explanation', models.TextField(blank=True, editable=False)),
                ('workflow_state', models.CharField(choices=[('intake', 'Intake'), ('assessment', 'Assessment'), ('intervention', 'Intervention Planning'), ('follow_up', 'Follow-up'), ('closed', 'Closed')], default='intake', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(help_text='Operator who submitted this entry.', on_delete=django.db.models.deletion.PROTECT, related_name='submitted_entries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sers_entries', to='cases.student')),
            ],
            options={
                'verbose_name': 'SERS Entry',
                'verbose_name_plural': 'SERS Entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InterventionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('parent_meeting', 'Parent Meeting'), ('tutoring', 'Tutoring'), ('counseling', 'Counselor Session'), ('referral', 'External Referral'), ('other', 'Other')], default='counseling', max_length=20)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('escalated', 'Escalated')], default='pending', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Supervisor responsible for this intervention.', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='cases.sersentry')),
            ],
            options={
                'verbose_name': 'Intervention Plan',
                'ordering': ('due_date',),
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('intake', 'Case created'), ('state_change', 'State change'), ('intervention', 'Intervention update'), ('reminder', 'Automatic reminder'), ('note', 'Note added'), ('denied', 'Action denied'), ('security', 'Security event')], max_length=20)),
                ('from_state', models.CharField(blank=True, max_length=20)),
                ('to_state', models.CharField(blank=True, max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_events', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.sersentry')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SERSPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_weight', models.PositiveSmallIntegerField(default=6)),
                ('grade_drop_weight', models.PositiveSmallIntegerField(default=5)),
                ('behavior_weight', models.PositiveSmallIntegerField(default=8)),
                ('wellbeing_weight', models.PositiveSmallIntegerField(default=10)),
                ('high_threshold', models.PositiveSmallIntegerField(default=65, help_text='SERS >= this value → HIGH risk.')),
                ('medium_threshold', models.PositiveSmallIntegerField(default=40, help_text='SERS >= this value (and < high) → MEDIUM risk.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sers_policies_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SERS Policy',
                'verbose_name_plural': 'SERS Policies',
            },
        ),
        migrations.AddIndex(
            model_name='sersentry',
            index=models.Index(fields=['workflow_state', 'risk_level'], name='cases_serse_workflo_753932_idx'),
        ),
        migrations.AddIndex(
            model_name='sersentry',
            index=models.Index(fields=['-created_at'], name='cases_serse_created_1652b4_idx'),
        ),
    ]
